# RetailIQ — Data Understanding

## Objective

The objective of this notebook is to understand the Olist Brazilian E-Commerce dataset before performing data cleaning or transformation.

We will:

- Inspect the available datasets
- Understand the structure of each table
- Examine rows and columns
- Check data types
- Identify missing values
- Check duplicate records
- Understand relationships between tables
- Examine date ranges
- Identify the datasets and fields relevant to RetailIQ

> The raw dataset will not be modified in this notebook.

## Cell 1 — Import libraries

In [1]:
# Import pandas for loading, cleaning, and analyzing tabular data
import pandas as pd

# Import NumPy for numerical operations
import numpy as np

# Import Matplotlib for creating visualizations
import matplotlib.pyplot as plt

# Import Seaborn for statistical and exploratory visualizations
import seaborn as sns

# Import Path to work with file and folder paths in a platform-independent way
from pathlib import Path

# Display all columns when viewing DataFrames
pd.set_option("display.max_columns", None)

# Display up to 100 rows when viewing DataFrames
pd.set_option("display.max_rows", 100)

# Confirm that the required libraries have been imported successfully
print("Libraries loaded successfully.")

Libraries loaded successfully.

## Cell 2 — Set the data path

In [2]:
# Import Path so we can work with project folders reliably across operating systems
from pathlib import Path

# Define the location of the raw Olist dataset relative to this notebook
DATA_PATH = Path("../data/raw")

# Check that the expected data folder exists
print("Data folder exists:", DATA_PATH.exists())

# Display the path we are using
print("Data path:", DATA_PATH)

Data folder exists: True
Data path: ..\data\raw

## Cell 3 — Find the CSV files

In [3]:
# Find all CSV files inside the raw data folder
csv_files = sorted(DATA_PATH.glob("*.csv"))

# Count how many CSV files were found
print(f"Number of CSV files found: {len(csv_files)}")

# Display the name of every CSV file
for file in csv_files:
    print(file.name)

Number of CSV files found: 9
olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_orders_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv

## Cell 4 — Load the datasets

In [4]:
# Create an empty dictionary to store all Olist DataFrames
datasets = {}

# Loop through each CSV file
for file in csv_files:
    
    # Use the filename without ".csv" as the dictionary key
    dataset_name = file.stem
    
    # Read the CSV file into a pandas DataFrame
    datasets[dataset_name] = pd.read_csv(file)

# Confirm that all datasets have been loaded
print(f"Loaded {len(datasets)} datasets successfully.")

Loaded 9 datasets successfully.

In [5]:
# Display the number of rows and columns for every dataset
for name, df in datasets.items():
    print(f"{name}: {df.shape}")

olist_customers_dataset: (99441, 5)
olist_geolocation_dataset: (1000163, 5)
olist_order_items_dataset: (112650, 7)
olist_order_payments_dataset: (103886, 5)
olist_order_reviews_dataset: (99224, 7)
olist_orders_dataset: (99441, 8)
olist_products_dataset: (32951, 9)
olist_sellers_dataset: (3095, 4)
product_category_name_translation: (71, 2)

## Cell 6 -- Column names

In [6]:
# Display the column names for every dataset
# This helps us understand what information each table contains

for name, df in datasets.items():
    print(f"\n{'=' * 70}")
    print(f"DATASET: {name}")
    print(f"{'=' * 70}")
    
    # Display all column names
    print("Columns:")
    for column in df.columns:
        print(f"  - {column}")

======================================================================
DATASET: olist_customers_dataset
======================================================================
Columns:
  - customer_id
  - customer_unique_id
  - customer_zip_code_prefix
  - customer_city
  - customer_state

======================================================================
DATASET: olist_geolocation_dataset
======================================================================
Columns:
  - geolocation_zip_code_prefix
  - geolocation_lat
  - geolocation_lng
  - geolocation_city
  - geolocation_state

======================================================================
DATASET: olist_order_items_dataset
======================================================================
Columns:
  - order_id
  - order_item_id
  - product_id
  - seller_id
  - shipping_limit_date
  - price
  - freight_value

======================================================================
DATASET: olist_order_payments_dataset
======================================================================
Columns:
  - order_id
  - payment_sequential
  - payment_type
  - payment_installments
  - payment_value

======================================================================
DATASET: olist_order_reviews_dataset
======================================================================
Columns:
  - review_id
  - order_id
  - review_score
  - review_comment_title
  - review_comment_message
  - review_creation_date
  - review_answer_timestamp

======================================================================
DATASET: olist_orders_dataset
======================================================================
Columns:
  - order_id
  - customer_id
  - order_status
  - order_purchase_timestamp
  - order_approved_at
  - order_delivered_carrier_date
  - order_delivered_customer_date
  - order_estimated_delivery_date

======================================================================
DATASET: olist_products_dataset
======================================================================
Columns:
  - product_id
  - product_category_name
  - product_name_lenght
  - product_description_lenght
  - product_photos_qty
  - product_weight_g
  - product_length_cm
  - product_height_cm
  - product_width_cm

======================================================================
DATASET: olist_sellers_dataset
======================================================================
Columns:
  - seller_id
  - seller_zip_code_prefix
  - seller_city
  - seller_state

======================================================================
DATASET: product_category_name_translation
======================================================================
Columns:
  - product_category_name
  - product_category_name_english

## Cell 7 -- Data types and missing values

In [9]:
# Create a compact data-quality summary for every dataset
# This lets us review data types and missing values without producing huge output

for name, df in datasets.items():
    print(f"\n{'=' * 70}")
    print(f"DATASET: {name}")
    print(f"{'=' * 70}")
    
    # Create a summary containing column names, data types, and missing-value counts
    summary = pd.DataFrame({
        "Data Type": df.dtypes,
        "Missing Values": df.isnull().sum(),
        "Missing %": (df.isnull().sum() / len(df) * 100).round(2)
    })
    
    # Display the summary
    display(summary)

======================================================================
DATASET: olist_customers_dataset
======================================================================

                         Data Type  Missing Values  Missing %
customer_id                    str               0        0.0
customer_unique_id             str               0        0.0
customer_zip_code_prefix     int64               0        0.0
customer_city                  str               0        0.0
customer_state                 str               0        0.0

======================================================================
DATASET: olist_geolocation_dataset
======================================================================

                            Data Type  Missing Values  Missing %
geolocation_zip_code_prefix     int64               0        0.0
geolocation_lat               float64               0        0.0
geolocation_lng               float64               0        0.0
geolocation_city                  str               0        0.0
geolocation_state                 str               0        0.0

======================================================================
DATASET: olist_order_items_dataset
======================================================================

                    Data Type  Missing Values  Missing %
order_id                  str               0        0.0
order_item_id           int64               0        0.0
product_id                str               0        0.0
seller_id                 str               0        0.0
shipping_limit_date       str               0        0.0
price                 float64               0        0.0
freight_value         float64               0        0.0

======================================================================
DATASET: olist_order_payments_dataset
======================================================================

                     Data Type  Missing Values  Missing %
order_id                   str               0        0.0
payment_sequential       int64               0        0.0
payment_type               str               0        0.0
payment_installments     int64               0        0.0
payment_value          float64               0        0.0

======================================================================
DATASET: olist_order_reviews_dataset
======================================================================

                        Data Type  Missing Values  Missing %
review_id                     str               0       0.00
order_id                      str               0       0.00
review_score                int64               0       0.00
review_comment_title          str           87656      88.34
review_comment_message        str           58247      58.70
review_creation_date          str               0       0.00
review_answer_timestamp       str               0       0.00

======================================================================
DATASET: olist_orders_dataset
======================================================================

                              Data Type  Missing Values  Missing %
order_id                            str               0       0.00
customer_id                         str               0       0.00
order_status                        str               0       0.00
order_purchase_timestamp            str               0       0.00
order_approved_at                   str             160       0.16
order_delivered_carrier_date        str            1783       1.79
order_delivered_customer_date       str            2965       2.98
order_estimated_delivery_date       str               0       0.00

======================================================================
DATASET: olist_products_dataset
======================================================================

                           Data Type  Missing Values  Missing %
product_id                       str               0       0.00
product_category_name            str             610       1.85
product_name_lenght          float64             610       1.85
product_description_lenght   float64             610       1.85
product_photos_qty           float64             610       1.85
product_weight_g             float64               2       0.01
product_length_cm            float64               2       0.01
product_height_cm            float64               2       0.01
product_width_cm             float64               2       0.01

======================================================================
DATASET: olist_sellers_dataset
======================================================================

                       Data Type  Missing Values  Missing %
seller_id                    str               0        0.0
seller_zip_code_prefix     int64               0        0.0
seller_city                  str               0        0.0
seller_state                 str               0        0.0

======================================================================
DATASET: product_category_name_translation
======================================================================

                              Data Type  Missing Values  Missing %
product_category_name               str               0        0.0
product_category_name_english       str               0        0.0

## Cell 8 - Preview the data

In [8]:
# Display the first three rows of every dataset
# This helps us see what the actual records look like

for name, df in datasets.items():
    print(f"\n{'=' * 70}")
    print(f"DATASET: {name}")
    print(f"{'=' * 70}")
    
    # Display the first three records
    display(df.head(3))

======================================================================
DATASET: olist_customers_dataset
======================================================================

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP

======================================================================
DATASET: olist_geolocation_dataset
======================================================================

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP

======================================================================
DATASET: olist_order_items_dataset
======================================================================

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.0,17.87

======================================================================
DATASET: olist_order_payments_dataset
======================================================================

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71

======================================================================
DATASET: olist_order_reviews_dataset
======================================================================

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24

======================================================================
DATASET: olist_orders_dataset
======================================================================

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00

======================================================================
DATASET: olist_products_dataset
======================================================================

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0

======================================================================
DATASET: olist_sellers_dataset
======================================================================

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ

======================================================================
DATASET: product_category_name_translation
======================================================================

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto

In [10]:
# Check the number of duplicate rows in each dataset.
# Duplicate records can affect analysis, so we identify them before making any changes.

duplicate_summary = []

for name, df in datasets.items():
    duplicate_summary.append({
        "Dataset": name,
        "Total Rows": len(df),
        "Duplicate Rows": df.duplicated().sum(),
        "Unique Rows": df.drop_duplicates().shape[0]
    })

# Convert the results into a DataFrame for easy comparison
duplicate_summary = pd.DataFrame(duplicate_summary)

# Display the duplicate summary
display(duplicate_summary)

                             Dataset  Total Rows  Duplicate Rows  Unique Rows
0            olist_customers_dataset       99441               0        99441
1          olist_geolocation_dataset     1000163          261831       738332
2          olist_order_items_dataset      112650               0       112650
3       olist_order_payments_dataset      103886               0       103886
4        olist_order_reviews_dataset       99224               0        99224
5               olist_orders_dataset       99441               0        99441
6             olist_products_dataset       32951               0        32951
7              olist_sellers_dataset        3095               0         3095
8  product_category_name_translation          71               0           71

In [11]:
# Check the number of unique values in important ID columns.
# This helps us understand which columns may act as identifiers or keys.

id_columns = {
    "olist_customers_dataset": ["customer_id", "customer_unique_id"],
    "olist_order_items_dataset": ["order_id", "order_item_id", "product_id", "seller_id"],
    "olist_order_payments_dataset": ["order_id"],
    "olist_order_reviews_dataset": ["review_id", "order_id"],
    "olist_orders_dataset": ["order_id", "customer_id"],
    "olist_products_dataset": ["product_id"],
    "olist_sellers_dataset": ["seller_id"]
}

for dataset_name, columns in id_columns.items():
    df = datasets[dataset_name]
    
    print(f"\n{'=' * 70}")
    print(f"DATASET: {dataset_name}")
    print(f"{'=' * 70}")
    
    for column in columns:
        print(f"{column}: {df[column].nunique():,} unique values")

======================================================================
DATASET: olist_customers_dataset
======================================================================
customer_id: 99,441 unique values
customer_unique_id: 96,096 unique values

======================================================================
DATASET: olist_order_items_dataset
======================================================================
order_id: 98,666 unique values
order_item_id: 21 unique values
product_id: 32,951 unique values
seller_id: 3,095 unique values

======================================================================
DATASET: olist_order_payments_dataset
======================================================================
order_id: 99,440 unique values

======================================================================
DATASET: olist_order_reviews_dataset
======================================================================
review_id: 98,410 unique values
order_id: 98,673 unique values

======================================================================
DATASET: olist_orders_dataset
======================================================================
order_id: 99,441 unique values
customer_id: 99,441 unique values

======================================================================
DATASET: olist_products_dataset
======================================================================
product_id: 32,951 unique values

======================================================================
DATASET: olist_sellers_dataset
======================================================================
seller_id: 3,095 unique values

## Verify the keys

In [12]:
# Check whether important identifier combinations are unique.
# This helps us determine which columns or combinations of columns
# can act as keys when we connect the different datasets.

key_checks = {
    "Customers - customer_id": (
        datasets["olist_customers_dataset"],
        ["customer_id"]
    ),
    
    "Customers - customer_unique_id": (
        datasets["olist_customers_dataset"],
        ["customer_unique_id"]
    ),
    
    "Orders - order_id": (
        datasets["olist_orders_dataset"],
        ["order_id"]
    ),
    
    "Order Items - order_id + order_item_id": (
        datasets["olist_order_items_dataset"],
        ["order_id", "order_item_id"]
    ),
    
    "Products - product_id": (
        datasets["olist_products_dataset"],
        ["product_id"]
    ),
    
    "Sellers - seller_id": (
        datasets["olist_sellers_dataset"],
        ["seller_id"]
    )
}

# Check each candidate key for duplicate combinations
for name, (df, columns) in key_checks.items():
    
    # Count how many rows share the same values for the selected key
    duplicate_keys = df.duplicated(subset=columns).sum()
    
    # Count the number of unique key combinations
    unique_keys = df[columns].drop_duplicates().shape[0]
    
    print(f"\n{name}")
    print(f"  Columns: {columns}")
    print(f"  Unique key combinations: {unique_keys:,}")
    print(f"  Duplicate key rows: {duplicate_keys:,}")

Customers - customer_id
  Columns: ['customer_id']
  Unique key combinations: 99,441
  Duplicate key rows: 0

Customers - customer_unique_id
  Columns: ['customer_unique_id']
  Unique key combinations: 96,096
  Duplicate key rows: 3,345

Orders - order_id
  Columns: ['order_id']
  Unique key combinations: 99,441
  Duplicate key rows: 0

Order Items - order_id + order_item_id
  Columns: ['order_id', 'order_item_id']
  Unique key combinations: 112,650
  Duplicate key rows: 0

Products - product_id
  Columns: ['product_id']
  Unique key combinations: 32,951
  Duplicate key rows: 0

Sellers - seller_id
  Columns: ['seller_id']
  Unique key combinations: 3,095
  Duplicate key rows: 0

## Map the relationships

In [13]:
# Check whether foreign-key values in child tables exist
# in the corresponding parent tables.
# This helps us identify valid relationships and possible unmatched records.

relationship_checks = [
    {
        "relationship": "Orders → Customers",
        "child_df": datasets["olist_orders_dataset"],
        "child_column": "customer_id",
        "parent_df": datasets["olist_customers_dataset"],
        "parent_column": "customer_id"
    },
    {
        "relationship": "Order Items → Orders",
        "child_df": datasets["olist_order_items_dataset"],
        "child_column": "order_id",
        "parent_df": datasets["olist_orders_dataset"],
        "parent_column": "order_id"
    },
    {
        "relationship": "Order Items → Products",
        "child_df": datasets["olist_order_items_dataset"],
        "child_column": "product_id",
        "parent_df": datasets["olist_products_dataset"],
        "parent_column": "product_id"
    },
    {
        "relationship": "Order Items → Sellers",
        "child_df": datasets["olist_order_items_dataset"],
        "child_column": "seller_id",
        "parent_df": datasets["olist_sellers_dataset"],
        "parent_column": "seller_id"
    },
    {
        "relationship": "Payments → Orders",
        "child_df": datasets["olist_order_payments_dataset"],
        "child_column": "order_id",
        "parent_df": datasets["olist_orders_dataset"],
        "parent_column": "order_id"
    },
    {
        "relationship": "Reviews → Orders",
        "child_df": datasets["olist_order_reviews_dataset"],
        "child_column": "order_id",
        "parent_df": datasets["olist_orders_dataset"],
        "parent_column": "order_id"
    }
]

# Test each relationship
for relationship in relationship_checks:
    
    # Get the unique foreign-key values from the child table
    child_keys = set(
        relationship["child_df"][relationship["child_column"]].dropna().unique()
    )
    
    # Get the valid primary-key values from the parent table
    parent_keys = set(
        relationship["parent_df"][relationship["parent_column"]].dropna().unique()
    )
    
    # Find child keys that do not exist in the parent table
    unmatched_keys = child_keys - parent_keys
    
    print(f"\n{relationship['relationship']}")
    print(f"  Child unique keys: {len(child_keys):,}")
    print(f"  Unmatched keys: {len(unmatched_keys):,}")

Orders → Customers
  Child unique keys: 99,441
  Unmatched keys: 0

Order Items → Orders
  Child unique keys: 98,666
  Unmatched keys: 0

Order Items → Products
  Child unique keys: 32,951
  Unmatched keys: 0

Order Items → Sellers
  Child unique keys: 3,095
  Unmatched keys: 0

Payments → Orders
  Child unique keys: 99,440
  Unmatched keys: 0

Reviews → Orders
  Child unique keys: 98,673
  Unmatched keys: 0

In [14]:
# Check whether product categories in the products table
# have corresponding English translations.
# This will help us understand whether the translation table
# can be safely joined to the product data.

products = datasets["olist_products_dataset"]
translations = datasets["product_category_name_translation"]

# Get the unique product categories from the products table
product_categories = set(
    products["product_category_name"].dropna().unique()
)

# Get the categories available in the translation table
translated_categories = set(
    translations["product_category_name"].dropna().unique()
)

# Find product categories that do not have a translation
untranslated_categories = product_categories - translated_categories

print(f"Unique product categories: {len(product_categories):,}")
print(f"Translated categories: {len(translated_categories):,}")
print(f"Categories without translation: {len(untranslated_categories):,}")

# Display the categories that do not have a translation
if untranslated_categories:
    print("\nCategories without translation:")
    for category in sorted(untranslated_categories):
        print(f"  - {category}")

Unique product categories: 73
Translated categories: 71
Categories without translation: 2

Categories without translation:
  - pc_gamer
  - portateis_cozinha_e_preparadores_de_alimentos

In [15]:
# Analyze the distribution of order statuses.
# This helps us understand the different stages of the order lifecycle
# before deciding which orders should be included in sales analysis.

orders = datasets["olist_orders_dataset"]

# Count the number of orders for each status
order_status_counts = orders["order_status"].value_counts()

# Display the order status counts
display(order_status_counts)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [16]:
# Calculate the percentage of orders represented by each status.
# This gives us a better understanding of the relative importance
# of each stage in the order lifecycle.

order_status_percentage = (
    orders["order_status"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
    .rename("Percentage")
)

# Display the percentage distribution
display(order_status_percentage)

order_status
delivered      97.02
shipped         1.11
canceled        0.63
unavailable     0.61
invoiced        0.32
processing      0.30
created         0.01
approved        0.00
Name: Percentage, dtype: float64

In [17]:
# Convert the order purchase timestamp from text to datetime.
# We create a temporary datetime column for analysis without changing
# the original raw dataset stored in our data/raw folder.

orders["purchase_datetime"] = pd.to_datetime(
    orders["order_purchase_timestamp"]
)

# Display the earliest and latest order purchase dates
print("Earliest order:", orders["purchase_datetime"].min())
print("Latest order:", orders["purchase_datetime"].max())

Earliest order: 2016-09-04 21:15:19
Latest order: 2018-10-17 17:30:18

In [18]:
# Calculate the overall time span covered by the order data.
# This tells us how much historical data is available for analysis
# and eventually for sales forecasting.

date_range = (
    orders["purchase_datetime"].max()
    - orders["purchase_datetime"].min()
)

print(f"Order history: {date_range.days} days")
print(f"Approximately {date_range.days / 365.25:.2f} years of data")

Order history: 772 days
Approximately 2.11 years of data

In [19]:
# Convert the important order timestamp columns from text to datetime.
# We use errors="coerce" so invalid or missing values become NaT
# instead of causing the analysis to fail.

date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for column in date_columns:
    orders[column] = pd.to_datetime(
        orders[column],
        errors="coerce"
    )

# Display the earliest and latest date available for each timestamp column.
# This helps us understand the coverage of each stage of the order lifecycle.

date_summary = []

for column in date_columns:
    date_summary.append({
        "Column": column,
        "Earliest Date": orders[column].min(),
        "Latest Date": orders[column].max(),
        "Missing Values": orders[column].isna().sum()
    })

# Convert the results into a DataFrame for easy comparison.
date_summary = pd.DataFrame(date_summary)

display(date_summary)

,Column,Earliest Date,Latest Date,Missing Values
0,order_purchase_timestamp,2016-09-04 21:15:19,2018-10-17 17:30:18,0
1,order_approved_at,2016-09-15 12:16:38,2018-09-03 17:40:06,160
2,order_delivered_carrier_date,2016-10-08 10:34:01,2018-09-11 19:48:28,1783
3,order_delivered_customer_date,2016-10-11 13:46:32,2018-10-17 13:22:46,2965
4,order_estimated_delivery_date,2016-09-30 00:00:00,2018-11-12 00:00:00,0

## Order-item financial summary

In [20]:
# Analyze the financial fields in the order items table.
# This helps us understand product prices and shipping costs at the item level.

order_items = datasets["olist_order_items_dataset"]

# Calculate basic statistics for price and freight value
financial_summary = order_items[["price", "freight_value"]].describe().T

# Add the total amount for each financial field
financial_summary["Total"] = order_items[["price", "freight_value"]].sum()

# Display the financial summary
display(financial_summary)

,count,mean,std,min,25%,50%,75%,max,Total
price,112650.0,120.653739,183.633928,0.85,39.90,74.99,134.90,6735.00,13591643.70
freight_value,112650.0,19.990320,15.806405,0.00,13.08,16.26,21.15,409.68,2251909.54

## Understand how many items orders contain

In [21]:
# Count the number of items associated with each order.
# An order can contain multiple products, so this helps us understand
# the relationship between orders and order items.

items_per_order = (
    order_items
    .groupby("order_id")
    .size()
)

# Display summary statistics for items per order
display(items_per_order.describe())

count    98666.000000
mean         1.141731
std          0.538452
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         21.000000
dtype: float64

## Check payment structure

In [22]:
# Analyze the payment table to understand how payments are distributed
# across orders.

payments = datasets["olist_order_payments_dataset"]

# Count how many payment records are associated with each order
payments_per_order = (
    payments
    .groupby("order_id")
    .size()
)

# Display summary statistics
display(payments_per_order.describe())

count    99440.000000
mean         1.044710
std          0.381166
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         29.000000
dtype: float64

## Understand payment values

In [23]:
# Calculate basic statistics for payment values.
# This helps us understand the monetary amounts recorded in the payment table.

payment_summary = payments["payment_value"].describe()

# Display the payment statistics
display(payment_summary)

count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

In [24]:
# Aggregate product prices and freight costs at the order level.
# This prevents individual order-item rows from being treated as separate orders.

order_item_totals = (
    order_items
    .groupby("order_id")
    .agg(
        item_price=("price", "sum"),
        freight_value=("freight_value", "sum")
    )
    .reset_index()
)

# Calculate the total item-level amount including freight for each order.
order_item_totals["item_total"] = (
    order_item_totals["item_price"]
    + order_item_totals["freight_value"]
)

# Aggregate all payment records belonging to the same order.
# An order can have multiple payment records, so they must be summed first.

payment_totals = (
    payments
    .groupby("order_id")
    .agg(
        payment_value=("payment_value", "sum")
    )
    .reset_index()
)

# Combine the order-level item totals with order-level payment totals.
financial_comparison = order_item_totals.merge(
    payment_totals,
    on="order_id",
    how="outer"
)

# Display summary statistics for the two monetary measures.
display(
    financial_comparison[
        ["item_price", "freight_value", "item_total", "payment_value"]
    ].describe()
)

         item_price  freight_value    item_total  payment_value
count  98666.000000   98666.000000  98666.000000   99440.000000
mean     137.754076      22.823562    160.577638     160.990267
std      210.645145      21.650909    220.466087     221.951257
min        0.850000       0.000000      9.590000       0.000000
25%       45.900000      13.850000     61.980000      62.010000
50%       86.900000      17.170000    105.290000     105.290000
75%      149.900000      24.040000    176.870000     176.970000
max    13440.000000    1794.960000  13664.080000   13664.080000

In [25]:
# Calculate the overall totals for each financial measure.
# This lets us compare the item-level amount with the recorded payment amount.

financial_totals = pd.DataFrame({
    "Metric": [
        "Product Price",
        "Freight",
        "Product Price + Freight",
        "Payment Value"
    ],
    "Total": [
        financial_comparison["item_price"].sum(),
        financial_comparison["freight_value"].sum(),
        financial_comparison["item_total"].sum(),
        financial_comparison["payment_value"].sum()
    ]
})

# Display the overall financial totals.
display(financial_totals)

                    Metric        Total
0            Product Price  13591643.70
1                  Freight   2251909.54
2  Product Price + Freight  15843553.24
3            Payment Value  16008872.12

## Payment type distribution

In [26]:
# Analyze the different payment methods used by customers.
# This helps us understand the structure of the payment table.

payment_type_summary = (
    payments["payment_type"]
    .value_counts()
    .rename_axis("Payment Type")
    .reset_index(name="Number of Payments")
)

# Display the number of payment records for each payment type
display(payment_type_summary)

  Payment Type  Number of Payments
0  credit_card               76795
1       boleto               19784
2      voucher                5775
3   debit_card                1529
4  not_defined                   3

## Payment value by type

In [27]:
# Calculate the total and average payment value for each payment method.
# This helps us understand how monetary value is distributed across
# different payment types.

payment_value_by_type = (
    payments
    .groupby("payment_type")["payment_value"]
    .agg(["count", "sum", "mean"])
    .reset_index()
)

# Rename the columns to make the results easier to understand
payment_value_by_type.columns = [
    "Payment Type",
    "Number of Payments",
    "Total Payment Value",
    "Average Payment Value"
]

# Display the payment value breakdown
display(payment_value_by_type)

  Payment Type  Number of Payments  Total Payment Value  Average Payment Value
0       boleto               19784           2869361.27             145.034435
1  credit_card               76795          12542084.19             163.319021
2   debit_card                1529            217989.79             142.570170
3  not_defined                   3                 0.00               0.000000
4      voucher                5775            379436.87              65.703354